server:
  port: 1101
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000